import initWebReaderSW from '../src/ServiceWorker/sw';
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope & {
  __precacheManifest: string[] | undefined;
};

function enableSW() {
  /**
   * Here perform the setup for cacheing you application shell:
   *  - the manifest generated by our parcel plugin
   *  - and the static readium-css and fonts we inject into the html reader
   */
  precacheAndRoute(self.__precacheManifest ?? []);
  precacheAndRoute([
    '/css/ReadiumCSS-before.css',
    '/css/ReadiumCSS-default.css',
    '/css/ReadiumCSS-after.css',
    '/fonts/opendyslexic/opendyslexic.css',
  ]);

  /**
   * This will add a fetch event listener to handle p
   */
  initWebReaderSW();
}

if (
  process.env.NODE_ENV === 'development' &&
  process.env.ENABLE_SW !== 'true'
) {
  console.warn('SW disabled in development');
} else {
  enableSW();
}
